#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Contains Friend class for program. This class will model any third party that
the user will share files with.
"""

from utils.config import Config
conf = Config()


class Friend:
    def __init__(self, name, ip, port, public_key):
        """
        Constructor for the Friend class

        Params:
            name (str): Title of the friend
            ip (str): Public IP address
            port (int): Standard port to use for transfer / hole punching
            public_key (byte): Public key generated by pyNaCl

        Returns: None
        """
        self.name = name
        self.ip = ip
        self.port = port
        self.public_key = public_key

    def save_friend(self):
        """Save Friend to friends.ini file"""
        conf.friends[self.name] = {}
        conf.friends[self.name]["ip"] = self.ip
        conf.friends[self.name]["port"] = self.port
        conf.friends[self.name]["public_key"] = self.public_key.hex()
        conf.save_config(files="friends")


if __name__ == "__main__":
    pass
